{% set name = "sphinxcontrib-video" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1052553faf5f0e255e5e292fae3f5f2fdd295f8a80745d649bfcdbcb12581a69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6.9
    - setuptools >=61.2
    - wheel
    - pip
  run:
    - python >=3.6.9
    - sphinx

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.video
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/video
  summary: Allows embedding of HTML5 videos in sphinx
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ReimarBauer
