{% set name = "sphinxcontrib-video" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 75a033e71b7de124cc5902430b7ba818a1c6c377be6401d07e9f2329a95d5ca4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - sphinx

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.video
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sphinx-contrib/video
  summary: Allows embedding of HTML5 videos in sphinx
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ReimarBauer
    - hmaarrfk
